name: Playwright Tests

on:
  deployment_status:

# ${{ github.event.deployment_status.target_url }}: vercelでブランチごとの動的に生成されるURL
# ${{ github.event.deployment_status.environment_url }}: vercelでブランチごとの動的に生成されるURL
# ${{ github.event.deployment_status.environment }}: Production or Preview or Development
# https://vent-git-${{ env.BRANCH_NAME }}-biki-clouds-projects.vercel.app: ブランチのデプロイURL

jobs:
  run-playwright-tests:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "${{ github.event.deployment_status.deployment.ref }}"
      - name: Get branch name
        run: |
          echo "BRANCH_NAME=$(git show -s --pretty=%D HEAD | tr -s ',' '\n' | sed 's/^ //' | grep -e 'origin/' | head -1 | sed 's/\origin\///g')" >> $GITHUB_ENV
      - name: Set BASE_URL
        run: |
          if [ "${{ github.event.deployment_status.environment }}" = "Production" ]; then
            echo "BASE_URL=https://vent-beryl.vercel.app" >> $GITHUB_ENV
          else
            echo "BASE_URL=https://vent-git-${{ env.BRANCH_NAME }}-biki-clouds-projects.vercel.app"  >> $GITHUB_ENV
            # echo "BASE_URL=${{ github.event.deployment_status.target_url }}" >> $GITHUB_ENV
          fi
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright
        run: pnpm exec playwright install --with-deps
      - name: Run tests
        run: pnpm exec playwright test
        env:
          BASE_URL: ${{ env.BASE_URL }}
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30
